#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
# Configure redirection from /redirect_me

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Starting nginx service
sudo service nginx start

# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | sudo dd status=none of=/var/www/html/index.nginx-debian.html

# Setting up redirection
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/redirect_me
server {
    listen 80;
    listen [::]:80;

    server_name _;

    location /redirect_me {
        return 301 https://www.example.com/new_page;
    }
}
EOF'

# Creating symbolic link
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Testing nginx configuration
sudo nginx -t

# Restarting nginx
sudo systemctl restart nginx

echo -e "\nCompleted. ✅\n"
